packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@auth/core': 0.37.2
  '@auth/drizzle-adapter': ~1.10.0
  next-auth: 5.0.0-beta.25
  eslint: ^9.31.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.25.32
  '@tanstack/react-query': ^5.69.0
  '@trpc/client': ^11.1.0
  '@trpc/tanstack-react-query': ^11.1.0
  '@trpc/server': ^11.1.0
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
  - utf-8-validate
